### ISSUE TITLE
Error setup.py

### ISSUE THREAD

**Issue by Mapirlet** [taohan10200/CRA5#4]
Hello, 

Thank you for this work, we have some troubles installing your package. When running the following command inside the virtual environment:
```python setup.py install ```
we get the following error: 

**warning: no files found matching 'LICENSE'
warning: no files found matching '*.h' under directory 'third_party'
writing manifest file 'cra5.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
file cra5.py (for module cra5) not found
file cra5.py (for module cra5) not found
running build_ext
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/matthiaspirlet/opt/anaconda3/envs/cra5/include -fPIC -O2 -isystem /Users/matthiaspirlet/opt/anaconda3/envs/cra5/include -I/Users/matthiaspirlet/opt/anaconda3/envs/cra5/include/python3.10 -c flagcheck.cpp -o flagcheck.o -std=c++17
building 'cra5.ans' extension
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/matthiaspirlet/opt/anaconda3/envs/cra5/include -fPIC -O2 -isystem /Users/matthiaspirlet/opt/anaconda3/envs/cra5/include -bundle -undefined dynamic_lookup -o build/lib.macosx-10.9-x86_64-cpython-310/cra5/ans.cpython-310-darwin.so -mmacosx-version-min=10.14
clang: error: no input files**

We would like to draw your attention on this line:
```warning: no files found matching '*.h' under directory 'third_party'```
We checked the ```setup.py``` file, it refers to a `third_party` and `cpp_exts` folder but they are missing.
We suppose that it comes from the compressai repo. However we are still not able to install your package. 

Could you provide us some hints to help us. 

Thank you very much.

**Comment by taohan10200** [comment]
Hi,

Thanks for your attention and feedback about the CRA5.

We have fixed the issue, Please execute the git pull to update your repo and install it again.

If you have any more questions, please don't hesitate to let me know.

**Comment by Mapirlet** [comment]
Hello,

Thank you for your fast response and this update. However we still face some issues during the installation.

When using the ```setup.py```file, it first complains about torch installation. So we installed it manually.

After that, part of the installation went well but some packages are still missing when trying to launch the ```test.py```. Here are the list of packages we had to install manually:
```ModuleNotFoundError: No module named 'cdsapi’```
```ModuleNotFoundError: No module named 'yapf’```
```ModuleNotFoundError: No module named 'addict’```
```ModuleNotFoundError: No module named 'rich’```
```ModuleNotFoundError: No module named 'regex’```
```ModuleNotFoundError: No module named 'xarray’```
```ModuleNotFoundError: No module named 'timm’```
```ModuleNotFoundError: No module named ‘compressai’```
```ModuleNotFoundError: No module named 'dict_recursive_update’```
```ModuleNotFoundError: No module named 'flash_attn’```

Do you think it is a problem from our side, otherwise is it possible to fix it ?

Thank you very much.

**Comment by taohan10200** [comment]
This means some requirements are not installed in the current environment. We now modify the `setup.py` to let all required packages are installed before CRA5.  Pls git pull the latest repo and `pip install .`.
